name: konnecti
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.8
  http: ^1.4.0
  shared_preferences: ^2.5.3
  curved_navigation_bar: ^1.0.6
  provider: ^6.1.5
  lottie: ^3.3.1
  cached_network_image: ^3.4.1
  dio: ^5.9.0
  flutter_launcher_icons: ^0.14.4
  flutter_vector_icons: ^2.0.0
  flutter_secure_storage: ^9.2.4
  flutter_svg: ^2.2.1
  qr_flutter: ^4.1.0
  flutter_gen: ^5.11.0
  intl: ^0.20.2
  get: ^4.7.2
  connectivity_plus: ^7.0.0
  url_launcher: ^6.3.2
  webview_flutter: ^4.13.0
  slickpayapi: ^0.0.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  generate: true

  assets:
    - assets/images/jpg/
    - assets/images/png/
    - assets/images/svg/
    - assets/icons/png/
    - assets/icons/svg/
    - assets/lottie/
    - assets/Animation.json

flutter_icons:
  android: true
  ios: true
  image_path: "assets/images/png/logo.png"
